# Generated by Django 6.0.2 on 2026-02-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutsession_completed_workoutsession_xp_gained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.profile'),
        ),
    ]
