# Generated by Django 6.0.2 on 2026-02-16 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutsession_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.profile'),
        ),
    ]
