# Generated by Django 6.0.2 on 2026-02-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_gym_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='timestamp',
            new_name='timestamp_date',
        ),
    ]
